name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: rust
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: cargo build --release

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
